# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mega_admin', '0014_auto_20180617_1526'),
    ]