# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mega_admin', '0014_auto_20180617_1526'),
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_title', models.CharField(max_length=200, verbose_name='Module title')),
                ('module_subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Module subtitle')),
                ('module_show_option', models.CharField(default='all', max_length=10)),
                ('module_position', models.CharField(blank=True, max_length=200, null=True)),
                ('module_published', models.BooleanField(default=1)),
                ('module_language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mega_admin.Language')),
                ('module_menu_item', models.ManyToManyField(blank=True, null=True, to='mega_admin.MenuItem')),
            ],
            options={
                'verbose_name_plural': 'Modules',
                'db_table': 'module',
                'verbose_name': 'Module',
            },
        ),
        migrations.CreateModel(
            name='ModuleCustomHtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_custom_html_content', models.TextField(blank=True, null=True)),
                ('module_custom_html_layout', models.CharField(blank=True, max_length=200, null=True)),
                ('module_custom_html_module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module_custom_html_module_key', to='module.Module')),
            ],
            options={
                'verbose_name_plural': 'Modules custom HTML',
                'db_table': 'module_custom_html',
                'verbose_name': 'Module Custom HTML',
            },
        ),
        migrations.CreateModel(
            name='ModuleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type_title', models.CharField(max_length=200, verbose_name='Module type name')),
                ('module_type_alias', models.CharField(max_length=200, verbose_name='Module type alias')),
                ('module_type_description', models.CharField(max_length=2000, verbose_name='Module type description')),
            ],
            options={
                'verbose_name_plural': 'Module types',
                'db_table': 'module_type',
                'verbose_name': 'Module type',
            },
        ),
        migrations.AddField(
            model_name='module',
            name='module_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_type_key', to='module.ModuleType'),
        ),
    ]
