# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0006_auto_20180615_1451'),
        ('module', '0003_auto_20180622_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleArticleAccordion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_article_accordion_count', models.IntegerField(default=5)),
                ('module_article_accordion_feature', models.BooleanField(default=0)),
                ('module_article_accordion_button', models.CharField(default='read more', max_length=50)),
                ('module_article_accordion_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extension.ArticleCategory')),
                ('module_article_accordion_module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module_article_accordion_module_key', to='module.Module')),
            ],
            options={
                'verbose_name_plural': 'Module article accordions',
                'verbose_name': 'Module article accordion',
                'db_table': 'module_article_accordion',
            },
        ),
    ]
