# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_modulearticleaccordion'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulearticleaccordion',
            name='module_article_accordion_date',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='modulearticleaccordion',
            name='module_article_accordion_image',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='modulearticleaccordion',
            name='module_article_accordion_parent',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='modulearticleaccordion',
            name='module_article_accordion_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_article_accordion_category_key', to='extension.ArticleCategory'),
        ),
    ]
