# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_auto_20180623_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_position_key', to='template.TemplatePosition'),
        ),
        migrations.AlterField(
            model_name='modulearticleaccordion',
            name='module_article_accordion_button',
            field=models.CharField(blank=True, default='read more', max_length=50, null=True),
        ),
    ]
