# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0008_auto_20180628_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduleimageslider',
            old_name='module_image_slider_thumb_geight',
            new_name='module_image_slider_thumb_height',
        ),
        migrations.AddField(
            model_name='module',
            name='module_layout',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modulearticleaccordion',
            name='module_article_accordion_thumb',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='modulearticleaccordion',
            name='module_article_accordion_thumb_height',
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name='modulearticleaccordion',
            name='module_article_accordion_thumb_width',
            field=models.IntegerField(default=80),
        ),
    ]
