# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0009_auto_20180628_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduleimageslidercontent',
            options={'ordering': ['module_image_slider_content_order'], 'verbose_name': 'Module image slider content', 'verbose_name_plural': 'Module image slider contents'},
        ),
        migrations.AddField(
            model_name='moduleimageslidercontent',
            name='module_image_slider_content_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
