# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0010_auto_20180628_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleimageslider',
            name='module_image_slider_speed',
            field=models.IntegerField(default=2000),
        ),
    ]
