# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0011_auto_20180628_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['module_order'], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AddField(
            model_name='module',
            name='module_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='module_show_title',
            field=models.BooleanField(default=1),
        ),
    ]
