# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0010_auto_20180628_1024'),
        ('module', '0013_auto_20180628_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleArticleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_article_list_main_count', models.IntegerField(default=1)),
                ('module_article_list_main_image', models.BooleanField(default=1)),
                ('module_article_list_main_image_thumb', models.BooleanField(default=0)),
                ('module_article_list_main_intro', models.BooleanField(default=1)),
                ('module_article_list_main_intro_slice', models.IntegerField(default=140)),
                ('module_article_list_main_button', models.BooleanField(default=1)),
                ('module_article_list_main_button_text', models.CharField(default='Read more', max_length=100)),
                ('module_article_list_main_layout', models.CharField(blank=True, max_length=100, null=True)),
                ('module_article_list_link_count', models.IntegerField(default=5)),
                ('module_article_list_link_image', models.BooleanField(default=1)),
                ('module_article_list_link_image_thumb', models.BooleanField(default=1)),
                ('module_article_list_link_intro', models.BooleanField(default=1)),
                ('module_article_list_link_intro_slice', models.IntegerField(default=140)),
                ('module_article_list_link_button', models.BooleanField(default=1)),
                ('module_article_list_link_button_text', models.CharField(default='Read more', max_length=100)),
                ('module_article_list_link_layout', models.CharField(blank=True, max_length=100, null=True)),
                ('module_article_list_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_article_list_category_key', to='extension.ArticleCategory')),
                ('module_article_list_module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module_article_list_module_key', to='module.Module')),
            ],
            options={
                'verbose_name': 'Module Article list',
                'db_table': 'module_article_list',
                'verbose_name_plural': 'Module Article lists',
            },
        ),
    ]
