# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-03-28 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_category_title', models.CharField(max_length=200, verbose_name='Menu category name')),
                ('menu_category_alias', models.CharField(max_length=200, verbose_name='Menu category alias')),
                ('menu_category_description', models.CharField(max_length=2000, verbose_name='Menu category description')),
            ],
            options={
                'db_table': 'menu_category',
                'verbose_name': 'Menu category',
                'verbose_name_plural': 'Menu categories',
            },
        ),
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type_title', models.CharField(max_length=200, verbose_name='Menu type name')),
                ('menu_type_alias', models.CharField(max_length=200, verbose_name='Menu type alias')),
                ('menu_type_description', models.CharField(max_length=2000, verbose_name='Menu type description')),
                ('menu_type_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_type_category_key', to='mega_admin.MenuCategory', verbose_name='Menu type category')),
            ],
            options={
                'db_table': 'menu_type',
                'verbose_name': 'Menu type',
                'verbose_name_plural': 'Menu types',
            },
        ),
    ]
