# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-03-28 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_menu_title', models.CharField(max_length=200, verbose_name='Menu name')),
                ('menu_menu_alias', models.CharField(max_length=200, verbose_name='Menu alias')),
                ('menu_menu_description', models.CharField(max_length=2000, verbose_name='Menu description')),
            ],
            options={
                'db_table': 'menu_menu',
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
    ]
