# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-05-18 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega_admin', '0003_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='lang_default',
            field=models.BooleanField(default='1', verbose_name='language is default'),
        ),
    ]
