# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-05-18 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega_admin', '0004_language_lang_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='lang_default',
            field=models.BooleanField(default='0', verbose_name='language is default'),
        ),
    ]
