# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega_admin', '0005_auto_20180518_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_config_multi', models.BooleanField(default='0', verbose_name='Site is multilingual')),
            ],
            options={
                'db_table': 'language_config',
                'verbose_name': 'Language Configuration',
                'verbose_name_plural': 'Language Configurations',
            },
        ),
    ]
