# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega_admin', '0006_languageconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='languageconfiguration',
            name='lang_config_alias',
            field=models.CharField(blank=True, max_length=100, verbose_name='Language configuration alias'),
        ),
    ]
