# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0006_auto_20180615_1451'),
        ('mega_admin', '0007_languageconfiguration_lang_config_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_title', models.CharField(max_length=200, verbose_name='Menu Item Custom URL title')),
                ('menu_item_subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Menu item subtitle')),
                ('menu_item_position', models.IntegerField(default=0)),
                ('menu_item_published', models.BooleanField(default=1)),
                ('menu_item_language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mega_admin.Language')),
                ('menu_item_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mega_admin.MenuMenu')),
                ('menu_item_parent_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mega_admin.MenuItem')),
                ('menu_item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_type_key', to='mega_admin.MenuType')),
            ],
            options={
                'verbose_name_plural': 'Menu Items',
                'db_table': 'menu_item',
                'verbose_name': 'Menu Item',
            },
        ),
        migrations.CreateModel(
            name='MenuItemCategoryBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_category_blog_category', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_category_blog_category_key', to='extension.ArticleCategory')),
                ('menu_item_category_blog_menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mega_admin.MenuItem')),
            ],
            options={
                'verbose_name_plural': 'Menu Item Categories Blog',
                'db_table': 'menu_item_category_blog',
                'verbose_name': 'Menu Item Category Blog',
            },
        ),
        migrations.CreateModel(
            name='MenuItemCategoryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_category_list_category', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_category_list_category_key', to='extension.ArticleCategory')),
                ('menu_item_category_list_menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mega_admin.MenuItem')),
            ],
            options={
                'verbose_name_plural': 'Menu Item Categories List',
                'db_table': 'menu_item_category_list',
                'verbose_name': 'Menu Item Category List',
            },
        ),
        migrations.CreateModel(
            name='MenuItemCustomUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_custom_url', models.CharField(max_length=200, verbose_name='URL address that points menu item')),
                ('menu_item_custom_url_menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mega_admin.MenuItem')),
            ],
            options={
                'verbose_name_plural': 'Menu Items Custom URL',
                'db_table': 'menu_item_custom_url',
                'verbose_name': 'Menu Item Custom URL',
            },
        ),
        migrations.CreateModel(
            name='MenuItemSingleArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_single_article_article', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_single_article_article_key', to='extension.Article')),
                ('menu_item_single_article_menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mega_admin.MenuItem')),
            ],
            options={
                'verbose_name_plural': 'Menu Item Single Articles',
                'db_table': 'menu_item_single_article',
                'verbose_name': 'Menu Item Single Article',
            },
        ),
    ]
