# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160224_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_intro',
            field=models.TextField(verbose_name='\u0412\u0441\u0442\u043a\u043f\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439 \u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(verbose_name='\u041e\u0441\u043d\u043e\u0432\u043d\u043e\u0439 \u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='article_image_text',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='\u041f\u043e\u0434\u043f\u0438\u0441\u044c \u043a \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044e'),
        ),
    ]
