"""
Django settings for oguzkent project.

Generated by 'django-admin startproject' using Django 1.9.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import sys


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-$69ta+$(xnz%q5qz_g$5b1rz&b)os7@u4skf^cic@*2woff(i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_HOST_USER = 'info@turkmenweb.pro'
EMAIL_HOST_PASSWORD = 'Info.Turkmenweb.Pro'
EMAIL_PORT = 465
EMAIL_USE_SSL = True

# Application definition

INSTALLED_APPS = [
	# 'admin_tools',
	# 'admin_tools.theming',
	# 'admin_tools.menu',
	# 'admin_tools.dashboard',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'django.contrib.sitemaps',
	'mega_admin',
	'extension',
	'template',
	'module',
	'mathfilters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'turkmenweb.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [
			'/home/turkmenweb/turkmenweb/bin/turkmenweb/mega_admin/templates',
			'/home/turkmenweb/turkmenweb/bin/turkmenweb/mega_admin/templates/blocks',
			'/home/turkmenweb/turkmenweb/bin/turkmenweb/mega_admin/templates/blocks/sidebars',
			'/home/turkmenweb/turkmenweb/bin/turkmenweb/mega_admin/templates/blocks/languages',
			'/home/turkmenweb/turkmenweb/bin/turkmenweb/mega_admin/templates/blocks/menus',
			'/home/turkmenweb/turkmenweb/bin/turkmenweb/mega_admin/templates/blocks/menu_items',
			'/home/turkmenweb/turkmenweb/bin/turkmenweb/mega_admin/templates/blocks/captions',
			'/home/turkmenweb/turkmenweb/bin/turkmenweb/mega_admin/templates/forms',
			'/home/turkmenweb/turkmenweb/bin/turkmenweb/mega_admin/templates/modals',

			'/home/turkmenweb/turkmenweb/bin/turkmenweb/extension/templates/content/pages',
			'/home/turkmenweb/turkmenweb/bin/turkmenweb/extension/templates/content/forms',
			'/home/turkmenweb/turkmenweb/bin/turkmenweb/extension/templates/content/blocks',
			'/home/turkmenweb/turkmenweb/bin/turkmenweb/extension/templates/content/captions',

			#'/home/turkmenweb/turkmenweb/bin/turkmenweb/article/templates',
			'/home/turkmenweb/turkmenweb/bin/turkmenweb/turkmenweb/templates',
			'/home/turkmenweb/turkmenweb/bin/turkmenweb/turkmenweb/templates/blocks',

			#'/home/turkmenweb/turkmenweb/bin/turkmenweb/article/templates',
			'/home/turkmenweb/turkmenweb/bin/turkmenweb/module/templates/',
			'/home/turkmenweb/turkmenweb/bin/turkmenweb/module/templates/captions/',
			'/home/turkmenweb/turkmenweb/bin/turkmenweb/module/templates/blocks/',
			'/home/turkmenweb/turkmenweb/bin/turkmenweb/module/templates/frontend/',
			'/home/turkmenweb/turkmenweb/bin/turkmenweb/module/templates/frontend/modules',
			'/home/turkmenweb/turkmenweb/bin/turkmenweb/module/templates/pages/',
		],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'turkmenweb.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.postgresql',
		'NAME': 'turkmenweb',
		'USER': 'turkmenweb',
		'PASSWORD': 'turkmenweb.opentm.2017',
		'HOST': '10.121.62.111',
		'PORT': '5432',
	}
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.6/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

# STATICFILES_DIRS = (
#	os.path.join(os.path.dirname(BASE_DIR), 'static', 'static_dirs'),
#	#   'media', '/home/turkmenweb/turkmenweb/bin/turkmenweb/media/',
# )

#STATIC_ROOT = '/home/turkmenweb/turkmenweb/bin/turkmenweb/static/'

# STATIC_ROOT = os.path.join(BASE_DIR, "static/")

MEDIA_ROOT = os.path.join(BASE_DIR, "static/")
