# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='article_image_text',
            field=models.TextField(blank=True, null=True, verbose_name='\u041f\u043e\u0434\u043f\u0438\u0441\u044c \u043a \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044e'),
        ),
    ]
