# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mega_admin', '0007_languageconfiguration_lang_config_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_title', models.CharField(max_length=200, verbose_name='Template title')),
                ('template_alias', models.CharField(max_length=200, verbose_name='Template alias')),
                ('template_description', models.TextField(blank=True, verbose_name='Template description')),
                ('template_version', models.IntegerField(blank=True, null=True, verbose_name='Template version')),
                ('template_default', models.BooleanField(default=0)),
                ('template_main_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mega_admin.MenuMenu')),
            ],
            options={
                'verbose_name_plural': 'Templates',
                'db_table': 'template',
                'verbose_name': 'Template',
            },
        ),
        migrations.CreateModel(
            name='TemplatePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_position_name', models.CharField(max_length=200, verbose_name='Template position name')),
                ('template_position_alias', models.CharField(max_length=200, verbose_name='Template position alias')),
                ('template_position_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_position_template_key', to='template.Template', verbose_name='Template positions template')),
            ],
            options={
                'verbose_name_plural': 'Template positions',
                'db_table': 'template_position',
                'verbose_name': 'Template position',
            },
        ),
    ]
