# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-04 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(max_length=200, verbose_name='Menu item title')),
                ('menu_description', models.CharField(max_length=200, verbose_name='Menu description')),
                ('menu_type', models.CharField(choices=[('article', 'Single article'), ('article_list', 'Article list'), ('article_blog', 'Article blog'), ('meta_link', 'User defined link')], max_length=200, verbose_name='Select menu type')),
                ('menu_subitem', models.CharField(blank=True, max_length=200, verbose_name='Select upperitems ID')),
                ('menu_link', models.CharField(blank=True, max_length=190, verbose_name='Menu link')),
                ('menu_position', models.CharField(blank=True, max_length=200, verbose_name='Specify item position')),
                ('menu_language', models.CharField(blank=True, choices=[('ru', '\u0440\u0443\u0441\u0441\u043a\u0438\u0439'), ('en', '\u0430\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u0438\u0439'), ('tm', '\u0442\u0443\u0440\u043a\u043c\u0435\u043d\u0441\u043a\u0438\u0439')], max_length=9, verbose_name='\u042f\u0437\u044b\u043a')),
            ],
            options={
                'db_table': 'menu',
                'verbose_name': 'menu_item',
                'verbose_name_plural': 'menu items',
            },
        ),
    ]
