# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-03-30 14:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mega_admin', '0003_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extension', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='article_category_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 3, 30, 14, 23, 44, 54268, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='article_category_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mega_admin.Language'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='article_category_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='article_category_metadesc',
            field=models.CharField(max_length=2000, null=True, verbose_name='Article category Meta Description'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='article_category_metakey',
            field=models.CharField(default=1, max_length=2000, verbose_name='Article category Meta Keys'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='article_category_note',
            field=models.CharField(default=1, max_length=2000, verbose_name='Menu category note'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='article_category_parrent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_category_parrent_key', to='extension.ArticleCategory', verbose_name='Menu category name'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='article_category_published',
            field=models.BooleanField(default=1, verbose_name='ArticleCategory'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='article_category_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Article category created by'),
            preserve_default=False,
        ),
    ]
