# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-03-30 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0002_auto_20180330_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecategory',
            old_name='article_category_parrent',
            new_name='article_category_parent',
        ),
    ]
