# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-03-30 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0003_auto_20180330_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='article_category_description',
            field=models.TextField(blank=True, verbose_name='Menu category description'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='article_category_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_category_parent_key', to='extension.ArticleCategory', verbose_name='Menu category name'),
        ),
    ]
