# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 14:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mega_admin', '0007_languageconfiguration_lang_config_alias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extension', '0004_auto_20180330_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=250, verbose_name='Article title')),
                ('article_alias', models.CharField(max_length=250, verbose_name='Article alias')),
                ('article_intro', models.TextField(blank=True, null=True, verbose_name='Article intro (before read more)')),
                ('article_content', models.TextField(blank=True, null=True, verbose_name='Article content')),
                ('article_published', models.BooleanField(default=1, verbose_name='ArticleCategory')),
                ('article_metadesc', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Article category Meta Description')),
                ('article_metakey', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Article Meta Keys')),
                ('article_category_created_date', models.DateTimeField(auto_now_add=True, verbose_name='Article created date')),
                ('article_category_edited_date', models.DateTimeField(auto_now_add=True, verbose_name='Article modified date')),
                ('article_category_note', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Article notes')),
                ('article_category', models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, related_name='article_category_key', to='extension.ArticleCategory', verbose_name='Category to which belongs article')),
                ('article_category_language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mega_admin.Language')),
                ('article_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Article created by')),
            ],
            options={
                'verbose_name_plural': 'Article',
                'verbose_name': 'Article',
                'db_table': 'article',
            },
        ),
    ]
