# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0005_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_category_created_date',
            new_name='article_created_date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_category_edited_date',
            new_name='article_edited_date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_category_language',
            new_name='article_language',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_category_note',
            new_name='article_note',
        ),
    ]
