# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import extension.models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0006_auto_20180615_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to=extension.models.Article.get_image_path, verbose_name='Article main image'),
        ),
    ]
