# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0009_auto_20180628_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-article_published', 'id'], 'verbose_name': 'Article', 'verbose_name_plural': 'Article'},
        ),
    ]
